services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: space-arcade-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: space_arcade
      POSTGRES_USER: spacearcade
      POSTGRES_PASSWORD: password123
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    networks:
      - space-arcade-network

  # Backend API
  backend:
    image: juego_software-main-backend
    container_name: space-arcade-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 4000
      DATABASE_URL: postgres://spacearcade:password123@postgres:5432/space_arcade
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      CORS_ORIGIN: http://localhost:3000
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    networks:
      - space-arcade-network
    volumes:
      - ./backend/uploads:/app/uploads

  # Frontend React App
  frontend:
    image: juego_software-main-frontend
    container_name: space-arcade-frontend
    restart: unless-stopped
    environment:
      REACT_APP_API_URL: http://localhost:4000/api
      REACT_APP_WS_URL: http://localhost:4000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - space-arcade-network

volumes:
  postgres_data:

networks:
  space-arcade-network:
    driver: bridge
