services:
  - type: web
    name: space-arcade-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  - type: web
    name: space-arcade-backend
    env: node
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        fromService:
          type: web
          name: space-arcade-frontend
          property: host
      - key: DATABASE_URL
        fromDatabase:
          name: space-arcade-db
          property: connectionString

databases:
  - name: space-arcade-db
    databaseName: space_arcade
    user: spacearcade
